apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: floatingips.kubevirt.io
spec:
  group: kubevirt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                networkName:
                  type: string
                routerName:
                  type: string
                floatingIp:
                  type: string
                vmName:
                  type: string
                podName:
                  type: string
                lbName:
                  type: string
                fixedIp:
                  type: string
  scope: Cluster
  names:
    plural: floatingips
    singular: floatingip
    kind: FloatingIp
    shortNames:
    - fip
    - fips
