apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: loadbalancers.kubevirt.io
spec:
  group: kubevirt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                networkId:
                  type: string
                vip:
                  type: string
                members:
                  type: array
                  items:
                    type: string
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      protocol:
                        type: string
                      portRangeMax:
                        type: integer
                      portRangeMin:
                        type: integer
  scope: Cluster
  names:
    plural: loadbalancers
    singular: loadbalancer
    kind: LoadBalancer
    shortNames:
    - lb
    - lbs
