apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securitygrouprules.kubevirt.io
spec:
  group: kubevirt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                securityGroupId:
                  type: string
                direction:
                  type: string
                etherType:
                  type: string
                protocol:
                  type: string
                portRangeMax:
                  type: integer
                portRangeMin:
                  type: integer
                remoteGroupId:
                  type: string
                remoteIpPrefix:
                  type: string
  scope: Cluster
  names:
    plural: securitygrouprules
    singular: securitygrouprule
    kind: SecurityGroupRule
    shortNames:
    - sgr
    - sgrs
