apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualrouters.kubevirt.io
spec:
  group: kubevirt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                enableSnat:
                  type: boolean
                mac:
                  type: string
                external:
                  type: object
                  properties:
                    ip:
                      type: string
                    network:
                      type: string
                internal:
                  type: array
                  items:
                    type: string
                peerRouter:
                  type: object
                  properties:
                    ip:
                      type: string
                    mac:
                      type: string
  scope: Cluster
  names:
    plural: virtualrouters
    singular: virtualrouter
    kind: VirtualRouter
    shortNames:
    - vr
    - vrs
